// web/src/app/business/components/features.tsx
export const Features = () => {
  return (
    <div className="bg-gray-50 py-24 sm:py-32">
      <div className="mx-auto max-w-2xl px-6 lg:max-w-7xl lg:px-8">
        <h2 className="text-center text-base/7 font-semibold text-primary">
          Business Accounts
        </h2>
        <p className="mx-auto mt-2 max-w-lg text-center text-4xl font-semibold tracking-tight text-balance sm:text-5xl">
          Everything you need to have your business seen by dog owners
        </p>
        <div className="mt-10 grid gap-4 sm:mt-16 lg:grid-cols-3 lg:grid-rows-2">
          <div className="relative lg:row-span-2">
            <div className="absolute inset-px rounded-lg bg-white lg:rounded-l-4xl"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-[calc(var(--radius-lg)+1px)] lg:rounded-l-[calc(2rem+1px)]">
              <div className="px-8 pt-8 pb-3 sm:px-10 sm:pt-10 sm:pb-0">
                <p className="mt-2 text-lg font-medium tracking-tight text-gray-950 max-lg:text-center">
                  Priority placement
                </p>
                <p className="mt-2 max-w-lg text-sm/6 text-gray-600 max-lg:text-center">
                  Have your business show up first in search results and gain
                  more visibility on our homepage.
                </p>
              </div>
              <div className="@container relative min-h-120 w-full grow max-lg:mx-auto max-lg:max-w-sm">
                <div className="absolute inset-x-10 top-10 bottom-0 overflow-hidden rounded-t-[12cqw] border-x-[3cqw] border-t-[3cqw] border-gray-700 bg-gray-900 shadow-2xl">
                  <img
                    className="size-full object-cover object-top"
                    src="https://tailwindcss.com/plus-assets/img/component-images/bento-03-mobile-friendly.png"
                    alt=""
                  />
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-lg shadow-sm ring-1 ring-black/5 lg:rounded-l-4xl"></div>
          </div>
          <div className="relative max-lg:row-start-1">
            <div className="absolute inset-px rounded-lg bg-white max-lg:rounded-t-4xl"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-[calc(var(--radius-lg)+1px)] max-lg:rounded-t-[calc(2rem+1px)]">
              <div className="px-8 pt-8 sm:px-10 sm:pt-10">
                <p className="mt-2 text-lg font-medium tracking-tight text-gray-950 max-lg:text-center">
                  Claim or create
                </p>
                <p className="mt-2 max-w-lg text-sm/6 text-gray-600 max-lg:text-center">
                  Claim or create your business profile and start managing your
                  business information, photos, and events.
                </p>
              </div>
              <div className="flex flex-1 items-center justify-center px-8 max-lg:pt-10 max-lg:pb-12 sm:px-10 lg:pb-2">
                <img
                  className="w-full max-lg:max-w-xs"
                  src="https://tailwindcss.com/plus-assets/img/component-images/bento-03-performance.png"
                  alt=""
                />
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-lg shadow-sm ring-1 ring-black/5 max-lg:rounded-t-4xl"></div>
          </div>
          <div className="relative max-lg:row-start-3 lg:col-start-2 lg:row-start-2">
            <div className="absolute inset-px rounded-lg bg-white"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-[calc(var(--radius-lg)+1px)]">
              <div className="px-8 pt-8 sm:px-10 sm:pt-10">
                <p className="mt-2 text-lg font-medium tracking-tight text-gray-950 max-lg:text-center">
                  Multiple business locations
                </p>
                <p className="mt-2 max-w-lg text-sm/6 text-gray-600 max-lg:text-center">
                  Manage all your business locations in one place. Add, update,
                  and remove locations as needed.
                </p>
              </div>
              <div className="@container flex flex-1 items-center max-lg:py-6 lg:pb-2">
                <img
                  className="h-[min(152px,40cqw)] object-cover"
                  src="https://tailwindcss.com/plus-assets/img/component-images/bento-03-security.png"
                  alt=""
                />
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-lg shadow-sm ring-1 ring-black/5"></div>
          </div>
          <div className="relative lg:row-span-2">
            <div className="absolute inset-px rounded-lg bg-white max-lg:rounded-b-4xl lg:rounded-r-4xl"></div>
            <div className="relative flex h-full flex-col overflow-hidden rounded-[calc(var(--radius-lg)+1px)] max-lg:rounded-b-[calc(2rem+1px)] lg:rounded-r-[calc(2rem+1px)]">
              <div className="px-8 pt-8 pb-3 sm:px-10 sm:pt-10 sm:pb-0">
                <p className="mt-2 text-lg font-medium tracking-tight text-gray-950 max-lg:text-center">
                  Events and promotions
                </p>
                <p className="mt-2 max-w-lg text-sm/6 text-gray-600 max-lg:text-center">
                  Create and advertise events and promotions.
                </p>
              </div>
              <div className="relative min-h-120 w-full grow">
                <div className="absolute top-10 right-0 bottom-0 left-10 overflow-hidden rounded-tl-xl bg-gray-900 shadow-2xl">
                  <div className="flex bg-gray-800/40 ring-1 ring-white/5">
                    <div className="-mb-px flex text-sm/6 font-medium text-gray-400">
                      <div className="border-r border-b border-r-white/10 border-b-white/20 bg-white/5 px-4 py-2 text-white">
                        NotificationSetting.jsx
                      </div>
                      <div className="border-r border-gray-600/10 px-4 py-2">
                        App.jsx
                      </div>
                    </div>
                  </div>
                  <div className="px-6 pt-6 pb-14">
                    {/* Your code example */}
                  </div>
                </div>
              </div>
            </div>
            <div className="pointer-events-none absolute inset-px rounded-lg shadow-sm ring-1 ring-black/5 max-lg:rounded-b-4xl lg:rounded-r-4xl"></div>
          </div>
        </div>
      </div>
    </div>
  );
};

// svelte/src/routes/business/components/features.svelte
<script lang="ts"></script>

<div class="bg-gray-50 py-24 sm:py-32">
	<div class="mx-auto max-w-2xl px-6 lg:max-w-7xl lg:px-8">
		<h2 class="text-primary text-center text-base/7 font-semibold">Business Accounts</h2>
		<p
			class="mx-auto mt-2 max-w-lg text-balance text-center text-4xl font-semibold tracking-tight sm:text-5xl"
		>
			Everything you need to have your business seen by dog owners
		</p>
		<div class="mt-10 grid gap-4 sm:mt-16 lg:grid-cols-3 lg:grid-rows-2">
			<!-- Priority -->
			<div class="relative lg:row-span-2">
				<div class="lg:rounded-l-4xl absolute inset-px rounded-lg bg-white"></div>
				<div
					class="relative flex h-full flex-col overflow-hidden rounded-[calc(var(--radius-lg)+1px)] lg:rounded-l-[calc(2rem+1px)]"
				>
					<div class="px-8 pb-3 pt-8 sm:px-10 sm:pb-0 sm:pt-10">
						<p class="mt-2 text-lg font-medium tracking-tight max-lg:text-center">
							Priority Placement
						</p>
						<p class="mt-2 max-w-lg text-sm/6 text-gray-600 max-lg:text-center">
							Have your business show up first in search results and gain more visibility on our
							homepage.
						</p>
					</div>
					<div class="@container min-h-120 relative w-full grow max-lg:mx-auto max-lg:max-w-sm">
						<div
							class="absolute inset-x-10 bottom-0 top-10 overflow-hidden rounded-t-[12cqw] border-x-[3cqw] border-t-[3cqw] border-gray-700 bg-gray-900 shadow-2xl"
						>
							<img
								class="size-full object-cover object-top"
								src="https://tailwindcss.com/plus-assets/img/component-images/bento-03-mobile-friendly.png"
								alt=""
							/>
						</div>
					</div>
				</div>
				<div
					class="lg:rounded-l-4xl pointer-events-none absolute inset-px rounded-lg shadow-sm ring-1 ring-black/5"
				></div>
			</div>
			<!-- Claim -->
			<div class="relative max-lg:row-start-1">
				<div class="max-lg:rounded-t-4xl absolute inset-px rounded-lg bg-white"></div>
				<div
					class="relative flex h-full flex-col overflow-hidden rounded-[calc(var(--radius-lg)+1px)] max-lg:rounded-t-[calc(2rem+1px)]"
				>
					<div class="px-8 pt-8 sm:px-10 sm:pt-10">
						<p class="mt-2 text-lg font-medium tracking-tight text-gray-950 max-lg:text-center">
							Claim or create
						</p>
						<p class="mt-2 max-w-lg text-sm/6 text-gray-600 max-lg:text-center">
							Claim or create your business profile and start managing your business information,
							photos, and events.
						</p>
					</div>
					<div
						class="flex flex-1 items-center justify-center px-8 max-lg:pb-12 max-lg:pt-10 sm:px-10 lg:pb-2"
					>
						<img
							class="w-full max-lg:max-w-xs"
							src="https://tailwindcss.com/plus-assets/img/component-images/bento-03-performance.png"
							alt=""
						/>
					</div>
				</div>
				<div
					class="max-lg:rounded-t-4xl pointer-events-none absolute inset-px rounded-lg shadow-sm ring-1 ring-black/5"
				></div>
			</div>
			<!-- Multiple -->
			<div class="relative max-lg:row-start-3 lg:col-start-2 lg:row-start-2">
				<div class="absolute inset-px rounded-lg bg-white"></div>
				<div
					class="relative flex h-full flex-col overflow-hidden rounded-[calc(var(--radius-lg)+1px)]"
				>
					<div class="px-8 pt-8 sm:px-10 sm:pt-10">
						<p class="mt-2 text-lg font-medium tracking-tight text-gray-950 max-lg:text-center">
							Multiple business locations
						</p>
						<p class="mt-2 max-w-lg text-sm/6 text-gray-600 max-lg:text-center">
							Manage all your business locations in one place. Add, update, and remove locations as
							needed.
						</p>
					</div>
					<div class="@container flex flex-1 items-center max-lg:py-6 lg:pb-2">
						<img
							class="h-[min(152px,40cqw)] object-cover"
							src="https://tailwindcss.com/plus-assets/img/component-images/bento-03-security.png"
							alt=""
						/>
					</div>
				</div>
				<div
					class="pointer-events-none absolute inset-px rounded-lg shadow-sm ring-1 ring-black/5"
				></div>
			</div>
			<!-- Events -->
			<div class="relative lg:row-span-2">
				<div
					class="max-lg:rounded-b-4xl lg:rounded-r-4xl absolute inset-px rounded-lg bg-white"
				></div>
				<div
					class="relative flex h-full flex-col overflow-hidden rounded-[calc(var(--radius-lg)+1px)] max-lg:rounded-b-[calc(2rem+1px)] lg:rounded-r-[calc(2rem+1px)]"
				>
					<div class="px-8 pb-3 pt-8 sm:px-10 sm:pb-0 sm:pt-10">
						<p class="mt-2 text-lg font-medium tracking-tight text-gray-950 max-lg:text-center">
							Events and promotions
						</p>
						<p class="mt-2 max-w-lg text-sm/6 text-gray-600 max-lg:text-center">
							Create and advertise events and promotions.
						</p>
					</div>
					<div class="min-h-120 relative w-full grow">
						<div
							class="absolute bottom-0 left-10 right-0 top-10 overflow-hidden rounded-tl-xl bg-gray-900 shadow-2xl"
						>
							<div class="flex bg-gray-800/40 ring-1 ring-white/5">
								<div class="-mb-px flex text-sm/6 font-medium text-gray-400">
									<div
										class="border-b border-r border-b-white/20 border-r-white/10 bg-white/5 px-4 py-2 text-white"
									>
										NotificationSetting.jsx
									</div>
									<div class="border-r border-gray-600/10 px-4 py-2">App.jsx</div>
								</div>
							</div>
							<div class="px-6 pb-14 pt-6">
								<!-- {/* Your code example */} -->
							</div>
						</div>
					</div>
				</div>
				<div
					class="max-lg:rounded-b-4xl lg:rounded-r-4xl pointer-events-none absolute inset-px rounded-lg shadow-sm ring-1 ring-black/5"
				></div>
			</div>
		</div>
	</div>
</div>
