// svelte/src/routes/verify-otp/+page.svelte
<script lang="ts">
	import { OtpForm } from './components/index';

	let { data } = $props();
	let { searchParams } = $derived(data);
</script>

<div class="flex min-h-svh flex-col items-center justify-center p-6 md:p-10">
	<h1 class="text-3xl">Enter OTP Code</h1>
	<div class="mt-6 flex flex-col text-center">
		<OtpForm {searchParams} />
	</div>
</div>

// web/src/app/(auth)/verify-otp/page.tsx
import { redirect } from "next/navigation";
import { OtpForm } from "./components/otp-form";

interface Props {
  searchParams: {
    [key: string]: string | string[] | undefined;
  };
}

const VerifyOTPPage = async ({ searchParams }: Props) => {
  if (!searchParams.email) {
    redirect("/sign-in");
  }

  const params = await searchParams;

  return (
    <div className="flex min-h-svh flex-col items-center justify-center p-6 md:p-10">
      <h1 className="text-3xl">Enter OTP Code</h1>
      <div className="flex flex-col text-center mt-6">
        <OtpForm searchParams={params} />
      </div>
    </div>
  );
};

export default VerifyOTPPage;
