// web/src/app/business/page.tsx
import { Navbar } from "@/components/navbar";
import { createClient } from "@/lib/supabase/server";
import { Hero } from "./components/hero";
import { Features } from "./components/features";
import { Footer } from "@/components/footer";
import { Pricing } from "./components/pricing";

const BusinessPage = async () => {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <div>
      <Navbar user={user} />
      <Hero />
      <Features />
      <Pricing />
      <Footer />
    </div>
  );
};

export default BusinessPage;

// svelte/src/routes/business/+page.svelte
<script lang="ts">
	import Footer from '$lib/components/footer.svelte';
	import Navbar from '$lib/components/navbar.svelte';
	import Features from './components/features.svelte';
	import Hero from './components/hero.svelte';
	import Pricing from './components/pricing.svelte';

	let { data } = $props();
	let { user } = $derived(data);
</script>

<svelte:head>
	<title>Business</title>
	<meta name="description" content="Create or claim your dog-friendly business." />
</svelte:head>

<Navbar {user} />
<Hero />
<Features />
<Pricing />
<Footer />
