// svelte/src/routes/welcome/components/welcome-loader.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { createUser } from '$lib/api/auth/createUser';
	import { useQuery } from '@sveltestack/svelte-query';
	import LottieAnimation from '$lib/components/lottie-animation.svelte';
	import welcomeAnimation from '$lib/lottie/welcome.json';
	import type { Session } from '@supabase/supabase-js';

	// Receive session as a prop
	let { session }: { session: Session | null } = $props();

	console.log('WelcomeLoader - received session:', session);

	const queryResult = useQuery('welcome', () => createUser(session?.access_token), {
		refetchInterval: (query) => {
			return query?.isSynced ? false : 1000;
		},
		enabled: !!session?.access_token
	});

	$effect(() => {
		if ($queryResult.data?.isSynced) {
			goto($queryResult.data.redirectUrl);
		}
	});
</script>

<div class="flex flex-col items-center justify-center">
	<LottieAnimation animationData={welcomeAnimation} loop autoplay />
	<h1 class="text-xl sm:text-2xl">One moment while we sign you in...</h1>
</div>

// web/src/app/(auth)/welcome/components/welcome-loader.tsx
"use client";

import { createUser } from "@/api/auth/createUser";
import { LottieAnimation } from "@/components/lottie-animation";
import dogWalking from "@/lottie/dog-walking.json";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

export const WelcomeLoader = () => {
  const router = useRouter();

  const { data } = useQuery({
    queryKey: ["create-account"],
    queryFn: async () => createUser(),
    refetchInterval: (query) => {
      return query.state.data?.isSynced ? false : 1000;
    },
  });

  useEffect(() => {
    if (data?.isSynced) router.push(data.redirectUrl);
  }, [data, router]);
  return (
    <div className="flex flex-col justify-center items-center">
      <LottieAnimation
        animationData={dogWalking}
        autoplay
        loop
        className="w-[300px]"
      />
      <h1 className="text-xl sm:text-2xl">
        One moment while we sign you in...
      </h1>
    </div>
  );
};
