// svelte/src/routes/verify-otp/components/otpForm.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Button, buttonVariants } from '$lib/components/ui/button';
	import {
		InputOTP,
		InputOTPGroup,
		InputOTPSeparator,
		InputOTPSlot
	} from '$lib/components/ui/input-otp';
	import { Loader2 } from '@lucide/svelte';
	import type { SupabaseClient } from '@supabase/supabase-js';
	import { toast } from 'svelte-sonner';
	import { defaults, superForm } from 'sveltekit-superforms';
	import { zod4 } from 'sveltekit-superforms/adapters';
	import { z } from 'zod/v4';

	interface Props {
		searchParams: {
			[key: string]: string | string[] | undefined;
		};
		supabase: SupabaseClient;
	}

	let { searchParams, supabase }: Props = $props();

	let loading: boolean = $state(false);

	const formSchema = z.object({
		pin: z
			.string()
			.length(6, { message: 'Code must be exactly 6 digits' })
			.regex(/^\d+$/, { message: 'Code must contain only numbers' })
	});

	const form = superForm(defaults(zod4(formSchema)), {
		validators: zod4(formSchema),
		SPA: true,
		onUpdate: ({ form: f }) => {
			if (f.valid) {
			} else {
				toast.error('Please enter a valid 6-digit code.');
			}
		}
	});

	const { form: formData, enhance } = form;

	$effect(() => {
		if ($formData.pin && $formData.pin.length === 6) {
			verifyPin($formData.pin);
		}
	});

	const verifyPin = async (pin: string) => {
		try {
			const { error } = await supabase.auth.verifyOtp({
				email: searchParams.email as string,
				token: pin,
				type: 'email'
			});

			if (error) {
				loading = false;
				throw error;
			} else {
				toast.success('OTP verified successfully! Redirecting...');
				setTimeout(() => {
					goto('/welcome', { keepFocus: true });
				}, 3000);
			}
		} catch (error) {
			console.error('Error verifying OTP:', error);
			toast.error('Failed to verify OTP. Please try again.');
		} finally {
			loading = false;
		}
	};

	const requestNewCode = async () => {
		try {
			const { error } = await supabase.auth.signInWithOtp({
				email: searchParams.email as string,
				options: {
					shouldCreateUser: false
				}
			});

			if (error) {
				toast.error('Failed to get new code. Please try again.');
			} else {
				toast.success('New code sent! Please check your email.');
			}
		} catch (error) {
			console.error('Error requesting new code:', error);
			toast.error('Failed to request new code. Please try again.');
		}
	};
</script>

<div>
	{#if loading}
		<div class="flex-vol flex items-center justify-center gap-3">
			<Loader2 class="size-10 animate-spin" />
			<p>Verifying...</p>
		</div>
	{:else}
		<div>
			<p>
				Enter the 6 digit code sent to <span class="font-bold">
					{searchParams.email}
				</span>
			</p>
			<p>
				Didn't receive a code?
				<Button variant="link" onclick={requestNewCode}>Request a new code</Button>
			</p>
		</div>
	{/if}
</div>

// web/src/app/(auth)/verify-otp/components/otp-form.tsx
"use client";

import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/components/ui/input-otp";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormMessage,
} from "@/components/ui/form";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import config from "@/lib/config";

interface Props {
  searchParams: {
    [key: string]: string | string[] | undefined;
  };
}

const FormSchema = z.object({
  pin: z
    .string()
    .length(6, { message: "Code must be exactly 6 digits" })
    .regex(/^\d+$/, { message: "Code must contain only numbers" }),
});

export const OtpForm = ({ searchParams }: Props) => {
  const supabase = createClient();
  const router = useRouter();
  const [otpLoading, setOtpLoading] = useState<boolean>(false);

  console.log(searchParams);

  const form = useForm<z.infer<typeof FormSchema>>({
    resolver: zodResolver(FormSchema),
    defaultValues: {
      pin: "",
    },
  });

  // Watch for complete OTP entry and auto-submit
  const pin = form.watch("pin");
  useEffect(() => {
    if (pin.length === 6) {
      form.handleSubmit(onSubmit)();
    }
  }, [pin]);

  async function onSubmit(values: z.infer<typeof FormSchema>) {
    setOtpLoading(true);

    try {
      const { error } = await supabase.auth.verifyOtp({
        email: searchParams.email as string,
        token: values.pin,
        type: "email",
      });

      if (error) {
        toast.error("Incorrect code. Please try again.");
        form.reset();
        setOtpLoading(false);
        return;
      }

      router.push(`${config.domainName}/welcome`);
      toast.success("Verification successful! Redirecting...");
      router.refresh();
    } catch (error) {
      console.error("Error during verification:", error);
      toast.error("Something went wrong. Please try again.");
    } finally {
      setOtpLoading(false);
    }
  }

  const requestNewCode = async () => {
    try {
      const { error } = await supabase.auth.signInWithOtp({
        email: searchParams.email as string,
        options: {
          shouldCreateUser: false,
        },
      });

      if (error) {
        toast.error("Failed to get new code. Please try again.");
      } else {
        toast.success("New code sent! Please check your email.");
      }
    } catch (error) {
      console.log(error);
      toast.error("Something went wrong. Please try again.");
    }
  };

  return (
    <>
      {otpLoading ? (
        <div className="flex flex-col items-center justify-center gap-3 text-black dark:text-white">
          <Loader2 className="w-10 h-10 animate-spin" />
          <p>Verifying...</p>
        </div>
      ) : (
        <>
          <p>
            Enter the 6-digit code sent to{" "}
            <span className="font-bold text-black dark:text-white">
              {searchParams.email}
            </span>
          </p>
          <p>
            Didn&apos;t get a code?{" "}
            <span
              onClick={requestNewCode}
              role="button"
              className="text-primary font-semibold hover:underline"
            >
              Request a new code
            </span>
          </p>
          <p className="text-sm mt-5">
            Note: You can only request a code once every 60 seconds. Codes are
            only valid for 1 hour.
          </p>
          <div className="flex items-center justify-center mt-10">
            <div>
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)}>
                  <FormField
                    control={form.control}
                    name="pin"
                    render={({ field }) => (
                      <FormItem>
                        <FormControl>
                          <InputOTP maxLength={6} {...field}>
                            <InputOTPGroup>
                              <InputOTPSlot index={0} />
                              <InputOTPSlot index={1} />
                              <InputOTPSlot index={2} />
                              <InputOTPSeparator />
                              <InputOTPSlot index={3} />
                              <InputOTPSlot index={4} />
                              <InputOTPSlot index={5} />
                            </InputOTPGroup>
                          </InputOTP>
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <div className="flex justify-between items-center mt-6">
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => form.reset()}
                      disabled={otpLoading}
                    >
                      Clear
                    </Button>
                    <Button
                      type="submit"
                      disabled={pin.length !== 6 || otpLoading}
                    >
                      Verify
                    </Button>
                  </div>
                </form>
              </Form>
            </div>
          </div>
        </>
      )}
    </>
  );
};
