// svelte/src/lib/components/lottie-animation.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import { DotLottieSvelte, type Data } from '@lottiefiles/dotlottie-svelte';

	interface Props {
		loop: boolean;
		autoplay: boolean;
		animationData?: Data;
		className?: string;
	}

	let { loop, autoplay, animationData, className }: Props = $props();
</script>

<div class={cn(className)}>
	<DotLottieSvelte data={animationData} loop autoplay />
</div>

// web/src/components/lottie-animation.tsx
"use client";

import Lottie from "lottie-react";
import { cn } from "@/lib/utils";

interface Props {
  loop: boolean;
  autoplay: boolean;
  animationData: unknown;
  className?: string;
}

export const LottieAnimation = ({
  loop,
  autoplay,
  animationData,
  className,
}: Props) => {
  return (
    <div className={cn(className)}>
      <Lottie animationData={animationData} loop={loop} autoplay={autoplay} />
    </div>
  );
};
