// svelte/src/routes/explore/components/navbar.svelte
<script lang="ts">
	import type { BAUser } from '$lib/types/models';
	import { Button } from '$lib/components/ui/button';
	import * as Avatar from '$lib/components/ui/avatar/index.js';
	import { Search, Bell, MessageSquare, Heart } from '@lucide/svelte';
	import { getUserInitials } from '$lib/helpers';
	import UserNav from '$lib/components/user-nav.svelte';
	import NavbarSearch from '$lib/components/navbar-search.svelte';
	import FavouriteSheet from '$lib/components/favourite-sheet.svelte';

	interface Props {
		user: BAUser | null;
	}

	let { user }: Props = $props();
</script>

<nav class="sticky top-0 z-50 w-full border-b bg-white">
	<div class="mx-auto flex h-16 max-w-[1400px] items-center justify-between px-6">
		<div class="flex items-center gap-8">
			<!-- Logo/Brand -->
			<a href="/" class="flex items-center gap-2">
				<div class="bg-primary flex h-9 w-9 items-center justify-center rounded-lg">
					<span class="text-primary-foreground text-lg font-bold">🐕</span>
				</div>
				<span class="text-foreground text-xl font-bold">Woofs Welcome</span>
			</a>

			<!-- Navigation Links -->
			<div class="hidden items-center gap-1 md:flex">
				<a href="/explore">
					<Button variant="ghost" class="font-medium">Explore</Button>
				</a>
				<a href="/help">
					<Button variant="ghost" class="font-medium">Help</Button>
				</a>
			</div>
		</div>

		<!-- Center Section: Search -->
		<NavbarSearch />

		<!-- Right Section: Icons & User -->
		<div class="flex items-center gap-3">
			<!-- Notification Icon -->
			{#if user}
				<Button variant="ghost" size="icon" class="relative">
					<Bell class="h-5 w-5" />
					<span class="absolute right-1.5 top-1.5 h-2 w-2 rounded-full bg-red-500"></span>
				</Button>

				<FavouriteSheet />
			{/if}

			<!-- User Section -->
			{#if user}
				<div class="ml-2 flex items-center gap-3 border-l pl-3">
					<div class="hidden flex-col items-end md:flex">
						<span class="text-sm font-semibold">{user.name || 'User'}</span>
						<span class="text-muted-foreground text-xs">{user.email}</span>
					</div>
					<UserNav {user} />
				</div>
			{:else}
				<Button variant="default" class="ml-2">Sign In</Button>
			{/if}
		</div>
	</div>
</nav>

// web/src/components/navbar.tsx
import { User } from "@supabase/supabase-js";
import { AlignJustify, CircleUser, GalleryHorizontalEnd } from "lucide-react";
import { Button } from "./ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu";
import Link from "next/link";

interface Props {
  user: User | null;
}

export const Navbar = ({ user }: Props) => {
  return (
    <header className="flex items-center justify-between h-20 w-full shrink-0 px-4 md:px-12">
      <Link href="/" className="flex items-center gap-2">
        <GalleryHorizontalEnd />
        <span className="text-xl font-bold">Woofs Welcome</span>
      </Link>

      {user ? (
        <Button variant="ghost" className="rounded-full py-3 px-1">
          <CircleUser className="size-6" />
        </Button>
      ) : (
        <div className="flex items-center gap-2">
          <Button variant="ghost" className="">
            Create a business account
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" className="rounded-full py-3 px-1">
                <AlignJustify className="size-6" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <Link href="/sign-in">
                <DropdownMenuItem>Sign in</DropdownMenuItem>
              </Link>
              <Link href="/sign-up">
                <DropdownMenuItem>Sign up</DropdownMenuItem>
              </Link>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      )}
    </header>
  );
};
